In [5]:
from ultralytics import YOLO
from tqdm.auto import tqdm
import numpy as np
import os
import pandas as pd
import cv2
from ultralytics.yolo.utils.plotting import Annotator

In [6]:
# Load a model
model = YOLO('yolov8n-pose.pt') # load an official model

In [8]:
dataset_path = "M:/Datasets/shock_walk/Videos/"
files = [i for i in os.listdir(dataset_path) if i.split('.')[-1] == "mp4"]
lengths  = []

for file in tqdm(files[0:]):
    
    skeletons = None
    video = cv2.VideoCapture(dataset_path + file)
    ret = True
    
    while ret:
        ret, image = video.read()
        
        if not ret:
            break
        
        image = image[:,175:-175]
        
        results = model(image, verbose=False)
        keypoint = results[0].keypoints.cpu()
        
        if keypoint.shape[0] != 1:
            keypoint = keypoint[0].view(1, 17, 3)
        
        if type(skeletons) != type(None):
            skeletons = np.concatenate((skeletons, keypoint.numpy()))
        else:
            skeletons = keypoint.numpy()
            q
        annotator = Annotator(np.ascontiguousarray(image))
        annotator.kpts(keypoint[0])
        
        cv2.imshow("image", annotator.result())
        
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    
    frame_per_video = 30 * 60
    
    skeletons = skeletons[:frame_per_video]
    print(np.max(skeletons))
    
    lengths.append(len(skeletons))
    # np.save(f"{dataset_path}skeletons/{file[:-4]}.npy", skeletons)
    
cv2.destroyAllWindows()

  0%|          | 0/25 [00:00<?, ?it/s]

1261.3999
1747.9009
1750.7336
1763.2871
1759.3198
1755.5724
1184.4797
1776.809
1764.064
1828.2532
1798.964
1765.425
1157.1913
1735.2177
1764.686
1750.3223
1778.8751
1717.9465
1779.8052
1739.4338
1732.6732
1743.7256
1739.937
1763.2083
1155.7483


In [10]:
print(lengths)

[1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800, 1800]


In [11]:
skeleton_path = f"M:/Datasets/shock_walk/Videos/skeletons/{files[0][:-4]}.npy"
skeleton_data = np.load(skeleton_path, allow_pickle=True)
print(skeleton_data)

[[[     461.98       230.5     0.17189]
  [        457      209.93    0.038435]
  [     469.53      205.73    0.056968]
  ...
  [     501.63      899.25     0.99934]
  [     385.24      1181.6     0.99275]
  [     468.72      1155.6     0.99355]]

 [[     446.11      238.54     0.14644]
  [     442.52      216.26    0.040571]
  [     453.43      213.42    0.042317]
  ...
  [      498.8      900.22     0.99944]
  [     381.48        1180     0.99459]
  [     473.08        1158     0.99511]]

 [[      451.3      236.64     0.17409]
  [     448.75      216.03    0.044848]
  [     461.86       212.7    0.053431]
  ...
  [     500.72      896.56     0.99932]
  [     388.23      1180.2     0.99265]
  [     479.02        1150     0.99366]]

 ...

 [[     461.47      285.25     0.23886]
  [     458.12      266.24    0.068536]
  [      467.4      265.68     0.10419]
  ...
  [     469.53      961.57     0.99881]
  [     366.07      1172.7     0.99322]
  [     431.19      1231.4     0.99328]]

 [